apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: redis
  name: redis-configmap
data:
  redis.conf: |
    dir "/data"
    # requirepass foobared
    maxmemory 0
    maxmemory-policy volatile-lru
    rdbchecksum yes
    rdbcompression yes
    save 900 1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: redis
  selector:
    app: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0.11-alpine
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', 'sysctl -w net.core.somaxconn=1024 && exec su-exec redis redis-server $0'] # net.core.somaxconn default is 128
        args:
        - /data/conf/redis.conf
        securityContext:
          privileged: true
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /data/conf
          name: config
          readOnly: true
      initContainers:
      - name: disable-thp     # disable transparent huge pages
        image: busybox
        volumeMounts:
        - name: host-sys
          mountPath: /host-sys
        command: ["sh", "-c", "echo never >/host-sys/kernel/mm/transparent_hugepage/enabled"]
      volumes:
      - configMap:
          name: redis-configmap
        name: config
      - name: host-sys
        hostPath:
          path: /sys


