apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.13
        ports:
        - containerPort: 3306
        stdin: true
        tty: true
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "demo"
        - name: MYSQL_USER
          value: "demo"
        - name: MYSQL_PASSWORD
          value: "demo"
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci