apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-cnf
  labels:
    app: proxysql
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"
    errorlog="/var/lib/proxysql/proxysql.log"
    
    admin_variables=
    {
        admin_credentials="admin:admin;radmin:radmin"
        mysql_ifaces="0.0.0.0:6032"
    }
    mysql_variables=
    {
        threads=4
        max_connections=2048
        default_query_delay=0
        default_query_timeout=36000000
        have_compress=true
        poll_timeout=2000
        interfaces="0.0.0.0:6033"
        default_schema="information_schema"
        stacksize=1048576
        server_version="5.7.13"
        connect_timeout_server=3000
        monitor_username="hrsaas"
        monitor_password="hrsaas"
        monitor_history=600000
        monitor_connect_interval=60000
        monitor_ping_interval=10000
        monitor_read_only_interval=1500
        monitor_read_only_timeout=500
        ping_interval_server_msec=120000
        ping_timeout_server=500
        commands_stats=true
        sessions_sort=true
        connect_retries_on_failure=10
        set_query_lock_on_hostgroup="false"
    }
    mysql_users:
    (
        {
            username="root"
            password="root"
            active=1
            default_hostgroup=1
            max_connections=1500
        },
        {
            username="hrsaas"
            password="hrsaas"
            active=1
            default_hostgroup=1
            max_connections=1500
        }
    )
    mysql_query_rules:
    (
        {
            rule_id=1
            active=1
            match_pattern="^SELECT.*FOR UPDATE$"
            destination_hostgroup=1
            apply=1
        },
        {
            rule_id=2
            active=1
            match_pattern="^SELECT"
            destination_hostgroup=2
            apply=1
        }
    )
    mysql_servers:
    (
        {
            hostgroup_id=1
            hostname="hrsaasdb-0.hrsaasdb"
            port=3306
            max_connections=150
        },
        {
            hostgroup_id=2
            hostname="hrsaasdb-1.hrsaasdb"
            port=3306
            max_connections=150
        },
        {
            hostgroup_id=2
            hostname="hrsaasdb-2.hrsaasdb"
            port=3306
            max_connections=150
        }
    )
    mysql_replication_hostgroups:
    (
        {
            writer_hostgroup=1
            reader_hostgroup=2
            comment="hrsaas cluster"
        }
    )

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxysql
  name: proxysql
spec:
  selector:
    matchLabels:
      app: proxysql
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      containers:
      - image: proxysql/proxysql:2.0.17
        imagePullPolicy: IfNotPresent
        name: proxysql
        command: ["proxysql", "-f", "-D", "/var/lib/proxysql", "-c", "/etc/proxysql/proxysql.cnf"]
        ports:
        - containerPort: 6032
          name: admin
          protocol: TCP
        - containerPort: 6033
          name: mysql
          protocol: TCP
        stdin: true
        tty: true
        volumeMounts:
          - name: proxysql-cnf
            mountPath: /etc/proxysql
      volumes:
      - name: proxysql-cnf
        configMap:
          name: proxysql-cnf
     

---
apiVersion: v1
kind: Service
metadata:
  name: proxysql
  labels:
    app: proxysql
spec:
  ports:
  - name: admin
    port: 6032
    protocol: TCP
    targetPort: 6032
  - name: mysql
    port: 6033
    protocol: TCP
    targetPort: 6033
  selector:
    app: proxysql
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: proxysql-external
spec:
  ports:
  - name: proxy
    nodePort: 30066
    port: 6033
    protocol: TCP
    targetPort: 6033
  selector:
    app: proxysql
  type: NodePort